language: node_js
node_js:
- '0.10'
before_install:
- npm install -g bower
- npm install -g grunt-cli
install:
- ./init.sh
script:
- grunt ci
# Generated https://docs.saucelabs.com/ci-integrations/travis-ci/
# Encrypted SAUCE_USERNAME and SAUCE_ACCESS_KEY
env:
  global:
    - secure: Dx/Qyqu1kF56Z1Z4HI58O8iNZDt20cyyIMbmhYqIttDRpABi/KdwcmbitncRcHrwnmyEeDpaQgbtMgBXf/kNY/GWyd7+/SUbVsWDKNTDxFE7LDHPbAi+0cKsbdR1kseIepbfsVTRShei3+LqdaV1dI/gp56kubRBnIfTkGysMdw=
    - secure: Vk+C0wnQmdYJgPiUw8IclfwfRE61tSn1OXSpZOxaxuaUpj51IovOuAGGg7dlPHJObKieXFDmd5qQ+y7JyAfTuv4ALEwyvXy2EkCUSMo8Nd4QvB0oW8D898vJllu5STCIBE8+58VQAm7bUq3WQ46fNaiGEY6fpgOfPSPWwjB1RZc=
